"use client";

const tildaRows = [
  { number: "01", title: "Маркетинговая база, прототип и тексты", price: "24 000 ₽", items: ["Интервью с отделом продаж и сбор критериев выбора", "Экспресс-анализ конкурентов и существующего пути клиента", "Структура сайта, сценарии заявок и продающий прототип", "Тексты для главной, категорий, кейсов и заявочных блоков"] },
  { number: "02", title: "UX/UI-дизайн — desktop + mobile", price: "60 000 ₽", items: ["Визуальная концепция промышленного B2B-сайта", "Главная, каталог, категория, карточка решения и кейсы", "Сценарий «Получить расчёт под мою задачу»", "Система карточек, таблиц характеристик, кнопок и форм", "Полноценная адаптация ключевых экранов под мобильные устройства"] },
  { number: "03", title: "Реализация на Tilda", price: "71 000 ₽", items: ["Сборка утверждённого дизайна и адаптивной версии", "До 5 категорий каталога и единый шаблон товарной карточки", "Разделы: роботизированные решения, применение, кейсы, контакты", "Формы запроса КП, подбора робота и расчёта роботизированной ячейки", "Навигация, базовые анимации и подготовка к самостоятельному ведению"] },
  { number: "04", title: "Техническая настройка и запуск", price: "5 000 ₽", items: ["Домен, SSL, аналитика и цели", "Настройка отправки заявок в e-mail / Telegram / CRM при наличии доступа", "Базовое SEO: метатеги, ЧПУ, sitemap, robots и страница 404", "Размещение политики конфиденциальности, согласия и условий из материалов клиента", "Финальная проверка перед публикацией"] },
];

const wpRows = [
  ["01", "Маркетинговая база, прототип и тексты", "24 000 ₽"],
  ["02", "UX/UI-дизайн — desktop + mobile", "60 000 ₽"],
  ["03", "Адаптивная HTML/CSS/JS-вёрстка", "50 000 ₽"],
  ["04", "WordPress: кастомная тема, админ-панель, каталог, кейсы и формы", "80 000 ₽"],
  ["05", "Технический запуск: хостинг, защита, резервные копии, аналитика и SEO-база", "16 000 ₽"],
];

export default function Home() {
  return <main>
    <header className="topbar"><a className="brand" href="#top">ELIANORA / DIGITAL</a><span className="topbar-label">Коммерческое предложение · 2026</span><a className="topbar-link" href="#estimate">Смета ↓</a></header>
    <section className="hero" id="top">
      <div className="hero-index">01 / 08</div><p className="eyebrow">Для MAYTEC</p>
      <h1>Сайт для<br />промышленной<br /><i>роботизации.</i></h1>
      <div className="hero-bottom"><p>Каталог оборудования, роботизированные решения, выполненные кейсы и заявки на расчёт — в одном сильном B2B-сайте.</p><a href="#brief" className="button button-inverse">Смотреть предложение <span>↘</span></a></div>
      <div className="hero-rule" /><div className="hero-statement">Не интернет-магазин. Инструмент для продажи сложных инженерных решений.</div>
    </section>
    <section className="section brief" id="brief"><p className="section-number">02 / Задача</p><div className="section-content split-headline"><h2>Не объединять<br />всё подряд.</h2><div className="large-copy"><p>Новый сайт нужен не для всех направлений MAYTEC, а именно для роботизации: промышленной автоматизации, роботов, ячеек и периферийного оборудования.</p><p>Металлоконструкции остаются самостоятельным направлением. На новом сайте — только спокойная отсылка: <a href="https://www.konstrust.pro/" target="_blank" rel="noreferrer">«Нужны металлоконструкции? Перейти на Kontrust ↗»</a>.</p></div></div></section>
    <section className="section architecture"><p className="section-number">03 / Логика сайта</p><div className="architecture-title"><h2>Структура, которая<br />ведёт к заявке.</h2><p>Берём полезную логику отраслевых сайтов: отдельно каталог, готовые комплексы, применение и реализованные проекты. Не копируем референс — строим собственную систему под MAYTEC.</p></div><div className="route-grid"><article><b>01</b><h3>Главная</h3><p>Ключевые компетенции, доверие, отрасли, быстрый вход в каталог и комплексные решения.</p></article><article><b>02</b><h3>Каталог</h3><p>До 5 категорий: роботы, ячейки, позиционеры, периферия и другое оборудование.</p></article><article><b>03</b><h3>Решения</h3><p>Сварка, паллетирование, обслуживание станков и другие типовые задачи производства.</p></article><article><b>04</b><h3>Кейсы</h3><p>Реализованные проекты с задачей, составом решения, фото и призывом обсудить аналогичную задачу.</p></article><article><b>05</b><h3>Заявка</h3><p>«Получить расчёт», «Подобрать робота», «Запросить КП» — из каждого сценария.</p></article></div></section>
    <section className="section platform"><p className="section-number">04 / Платформа</p><div className="platform-grid"><div className="platform-intro"><h2>Две реализации.<br />Одна цель.</h2><p>На старте каталог до 50 позиций и заявки без онлайн-оплаты можно качественно реализовать на обеих платформах.</p></div><article className="platform-card dark"><p className="eyebrow">Рекомендуем на старте</p><h3>Tilda</h3><p>Быстрый запуск, понятное самостоятельное обновление, каталог и SEO-база без лишней технической нагрузки.</p><strong>от 160 000 ₽</strong></article><article className="platform-card"><p className="eyebrow">Если нужен рост логики</p><h3>WordPress</h3><p>Для сложной фильтрации, развития каталога, нестандартных интеграций и более гибкой административной части.</p><strong>от 230 000 ₽</strong></article></div><p className="platform-note">SEO зависит от структуры, качества контента и регулярного развития сайта — не от названия платформы. WordPress даёт больше свободы, но не автоматический рост позиций.</p></section>
    <section className="section estimate" id="estimate"><div className="estimate-head"><p className="section-number">05 / Подробная смета</p><div><p className="eyebrow">Вариант А</p><h2>Разработка на Tilda</h2></div><div className="estimate-total"><span>Итого</span><strong>160 000 ₽</strong></div></div><div className="estimate-table">{tildaRows.map((row) => <article className="estimate-row" key={row.number}><div className="row-number">{row.number}</div><div className="row-main"><h3>{row.title}</h3><ul>{row.items.map((item) => <li key={item}>{item}</li>)}</ul></div><div className="row-price">{row.price}</div></article>)}</div></section>
    <section className="section wp-estimate"><div className="estimate-head"><p className="section-number">06 / Альтернатива</p><div><p className="eyebrow">Вариант B</p><h2>Разработка на WordPress</h2></div><div className="estimate-total"><span>Итого</span><strong>230 000 ₽</strong></div></div><div className="wp-list">{wpRows.map(([num, title, price]) => <div className="wp-row" key={num}><span>{num}</span><p>{title}</p><b>{price}</b></div>)}</div><p className="fine-print">WordPress требует отдельного хостинга, регулярных обновлений и резервного копирования. После запуска техническую поддержку можно подключать по необходимости.</p></section>
    <section className="section catalog"><p className="section-number">07 / Наполнение каталога</p><div className="catalog-head"><h2>Товары —<br />отдельно от<br />разработки.</h2><p>В базовую стоимость не входит внесение товарных карточек. Можно выбрать ручную работу или загрузку подготовленного массива.</p></div><div className="catalog-grid"><article><p className="eyebrow">Вариант 01</p><h3>Импорт таблицей</h3><strong>от 300 ₽ <small>/ карточка</small></strong><p>Минимальная стоимость — 10 000 ₽. Подходит, если данные готовы в едином шаблоне.</p></article><article className="dark"><p className="eyebrow">Вариант 02</p><h3>Ручное внесение</h3><strong>от 800 ₽ <small>/ карточка</small></strong><p>Название, категория, фото, характеристики, описание, цена / «по запросу» и базовые SEO-поля.</p></article></div><div className="import-rule"><b>Чтобы импорт состоялся:</b><span>одна строка — один товар · согласованные категории · артикулы/ID · описание и характеристики · прямые ссылки на фото · цены или статус «по запросу» · SEO-поля при необходимости</span></div></section>
    <section className="section final"><p className="section-number">08 / Следующий шаг</p><h2>Фиксируем<br />первый релиз.</h2><div className="final-grid"><p>После выбора платформы проводим установочную встречу с отделом продаж. На ней фиксируем каталог, список ключевых страниц, приоритетные решения и материалы для кейсов.</p><p>Юридические тексты — политика конфиденциальности, согласие на обработку данных и условия работы — размещаются на сайте после предоставления и утверждения со стороны клиента.</p></div><div className="about"><div className="about-mark">EM</div><div><p className="eyebrow">Исполнитель</p><h3>Элионора Муллагалиева</h3><p>Стратегия, структура, контент, UX/UI-дизайн и сопровождение разработки в одном проекте.</p></div><a className="button" href="#top">Вернуться наверх <span>↑</span></a></div></section>
    <footer><span>© 2026 · Коммерческое предложение для MAYTEC</span><a href="https://www.konstrust.pro/" target="_blank" rel="noreferrer">Металлоконструкции → Kontrust ↗</a></footer>
  </main>;
}
